// Auto-mock for user.model.js — used by all tests that do jest.mock('...user.model')
// Every exported function is a jest.fn(). Route tests that need auth to pass
// rely on findById returning a non-null, non-suspended user.
module.exports = {
  findByEmail: jest.fn(),
  findByEmailIncludingDeleted: jest.fn(),
  isUsernameTaken: jest.fn(),
  findByUsername: jest.fn(),
  findByEmailOrUsername: jest.fn(),
  findById: jest.fn().mockResolvedValue({ id: 'user-1', sub: 'user-1', is_suspended: false }),
  findFullById: jest.fn(),
  findPublicById: jest.fn(),
  create: jest.fn(),
  createOAuthUser: jest.fn(),
  markVerified: jest.fn(),
  updateLastLogin: jest.fn(),
  updatePassword: jest.fn(),
  setPendingEmail: jest.fn(),
  applyPendingEmail: jest.fn(),
  softDeleteWithContent: jest.fn(),
  reviveUser: jest.fn(),
  isFollowing: jest.fn(),
  updateProfile: jest.fn(),
  updateAccount: jest.fn(),
  updateRole: jest.fn(),
  promoteListenerToArtist: jest.fn(),
  deleteAvatar: jest.fn(),
  updateAvatar: jest.fn(),
  updateCoverPhoto: jest.fn(),
  deleteCoverPhoto: jest.fn(),
  findWebProfilesByUserId: jest.fn(),
  findWebProfileByPlatform: jest.fn(),
  createWebProfile: jest.fn(),
  deleteWebProfile: jest.fn(),
  findWebProfileById: jest.fn(),
  updatePrivacy: jest.fn(),
  findContentSettingsByUserId: jest.fn(),
  updateContentSettings: jest.fn(),
  findPrivacySettingsByUserId: jest.fn(),
  updatePrivacySettings: jest.fn(),
  findGenresByUserId: jest.fn(),
  replaceGenres: jest.fn(),
  completeOnboarding: jest.fn(),
  findVisibleLikedTracksByUserId: jest.fn(),
  updateUserStatus: jest.fn(),
  getUserWarningCount: jest.fn(),
  getSuspendedAccountsCount: jest.fn(),
  getActiveUsersCount: jest.fn(),
  getActiveUsersToday: jest.fn(),
  getNewRegistrationsCount: jest.fn(),
};
